all:
	g++ -I/home/nicko/work/systemc-2.2.0/build/include -I/home/nicko/work/occn_3/include -std=c++11 -fPIC main.cpp -L/home/nicko/work/systemc-2.2.0/build/lib-linux64 -L/home/nicko/work/occn_3/lib-linux64 -no-pie -fpermissive -lsystemc -loccn -lpthread  -o minimal_com

